### ISSUE TITLE
Warn:  WARN - buildServer.AGENT.registration - Error registering on the server via URL http://teamcity-server:8111. Will continue repeating connection attempts. Details: server is in a maintenance mode

### ISSUE THREAD

**Issue by thanhpd56** [Egregors/teamcity-docker-compose#10]
Hi,
I try to deploy teamcity-docker to my EC2 instance.
I setup following your instruction, but after run docker-compose up -d, I receive this error, and the Teamcity Maintenance loading forever.

 WARN - buildServer.AGENT.registration - Error registering on the server via URL http://teamcity-server:8111. Will continue repeating connection attempts. Details: server is in a maintenance mode
Any suggestion? Please help me.

**Comment by egregors** [comment]
Greeting @thanhpd56, 
This is normal behavior, please pay attention to "[Updating maintenance](https://github.com/Egregors/teamcity-docker-compose#updating-maintenance)" section in README.

> Sometimes, during update you may get «maintenance is required» message instead of login page. It's ok! To login in a maintenance mode you need to enter an authentication token. You may find it in the logs: docker-compose logs -f

> Try to find something like this:

`     | [TeamCity] Administrator can login from web UI using authentication token: 8755994969038184734
`


You just should find authentication token in the Logs, and use it to log in.
