### ISSUE TITLE
Error while asking server for the communication protocols via URL : Team City

### ISSUE THREAD

**Issue by GokulendraPanda** [Egregors/teamcity-docker-compose#15]
**Server Running in Windows 
Install Agent in Linux** 
While registering agent error observed 
WARN - buildServer.AGENT.registration - Error while asking server for the communication protocols via URL http://xxx.xxx.xx.x:8111/app/agents/protocols. Will try later: java.net.ConnectException: Connection timed out (Connection timed out) (enable debug to see stacktrace)
[WARN - buildServer.AGENT.registration - Error registering on the server via URL http://xxx.xxx.xx.x:8111. Will continue repeating connection attempts.

**Comment by egregors** [comment]
Do you run standalone TeamCity on the Windows host (without docker), and trying connect agents from the docker-compose (with docker)?

**Comment by GokulendraPanda** [comment]
Yes exactly...

**Comment by egregors** [comment]
You can't get access to the compose containers from the outside, because Docker has his own network. You may try to expose 9090 port for agents. Or try to run whole compose (with docker) and move existing TeamCity backups into new server

**Comment by egregors** [comment]
@GokulendraPanda as I see, you successfully connected the agent to the server. Is it correct, we should close the issue.
