### ISSUE TITLE
Hostname of server container should be set using .env

### ISSUE THREAD

**Issue by eproxus** [Egregors/teamcity-docker-compose#17]
The hostname of the server container should be set to `$VIRTUAL_HOST`, otherwise email notifications won't work in TeamCity.

**Comment by egregors** [comment]
Okay, I'll fix it soon. Or if you have a quick solve, PR is welcome

**Comment by egregors** [comment]
@eproxus actually, I just tested mail sending on current settings and all work well. Do you sure that the reason for your problem is the hostname of the container?

**Comment by eproxus** [comment]
@Egregors Well, I changed it from `4c4aa472e1f5` to `ci.ourdomain.com` and then it worked. It seemed that TeamCity sends `HELO $(hostname)` when using StartTLS and it requires the hostname to be a qualified domain somehow.

**Comment by egregors** [comment]
@eproxus hm.. okay, I'll add hostname update in the next patch

**Comment by eproxus** [comment]
@Egregors Thanks!
