### ISSUE TITLE
Make Install Bug

### ISSUE THREAD

**Issue by QF0xB** [Egregors/teamcity-docker-compose#29]
## Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by QF0xB** [comment]
Seems to be fixed by changing the Node Version for Python in the agents directory to 14

**Comment by egregors** [comment]
@Stormfox2 Could you please make a PR for this?
