### ISSUE TITLE
include JDBC drivers

### ISSUE THREAD

**Issue by mindhaq** [Egregors/teamcity-docker-compose#3]
Manually downloading a JDBC driver into the TC container seems to be an unnecessary extra step, which should be provided.

Should be doable in a Dockerfile extending the official image.

**Comment by egregors** [comment]
@mindhaq Sounds reasonable. I'll try to improve TC server Dockerfile soon.

**Comment by mindhaq** [comment]
@Egregors there is one fork where it's already done

https://github.com/MCord/teamcity-docker-compose/commit/02a42ed6ca5c01c26bd96f5cf9b27d2353820b58

sadly, more stuff is done as well, so a PR is not really possible. maybe it's still useful.

**Comment by egregors** [comment]
@mindhaq Yep. Done. https://github.com/Egregors/teamcity-docker-compose/commit/3d117b04940edcbba402a5c41f8a222dd896facc
Plus little readme update and cleanup.
