### ISSUE TITLE
Failed to start build agent. For input string: "8111 "

### ISSUE THREAD

**Issue by pushkin-dev** [Egregors/teamcity-docker-compose#31]
help wanted....

log file:

`agent_1     | [2021-07-16 07:03:50,273]  ERROR - s.buildServer.agent.AgentMain2 - Failed to start build agent. For input string: "8111 "
agent_1     | java.lang.RuntimeException: For input string: "8111 "
agent_1     | 	at jetbrains.buildServer.xmlrpc.XmlRpcFactory.createCommonsHttpTransportTarget(XmlRpcFactory.java:85)
agent_1     | 	at jetbrains.buildServer.xmlrpc.XmlRpcFactory.create(XmlRpcFactory.java:118)
agent_1     | 	at jetbrains.buildServer.agent.impl.XmlRpcAgentLogListener.createTarget(XmlRpcAgentLogListener.java:60)
agent_1     | 	at jetbrains.buildServer.agent.impl.XmlRpcAgentLogListener.<init>(XmlRpcAgentLogListener.java:56)
agent_1     | 	at jetbrains.buildServer.agent.impl.XmlRpcAgentLogListener.<init>(XmlRpcAgentLogListener.java:45)
agent_1     | 	at jetbrains.buildServer.agent.impl.ServerXmlRpcProxy.<init>(ServerXmlRpcProxy.java:47)
agent_1     | 	at jetbrains.buildServer.agent.impl.BuildAgentImpl.init(BuildAgentImpl.java:865)
agent_1     | 	at jetbrains.buildServer.agent.AgentMain2.startAgent(AgentMain2.java:216)
agent_1     | 	at jetbrains.buildServer.agent.AgentMain2.main2(AgentMain2.java:92)
agent_1     | 	at jetbrains.buildServer.agent.AgentMain2.main(AgentMain2.java:39)
agent_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
agent_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
agent_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
agent_1     | 	at java.lang.reflect.Method.invoke(Method.java:498)
agent_1     | 	at jetbrains.buildServer.agent.AgentMain.main(AgentMain.java:43)
agent_1     | [2021-07-16 07:03:50,274]   INFO - ent.impl.upgrade.AgentExitCode - Agent exited. Failed to start build agent
agent_1     | [2021-07-16 07:03:50,275]   INFO - buildServer.agent.AgentMain2$3 - Closing jetbrains.buildServer.agent.AgentMain2$3@9a7504c: startup date [Fri Jul 16 07:03:38 BST 2021]; root of context hierarchy
`
.env file:
`POSTGRES_PASSWORD=tc_password
POSTGRES_USER=tc_pg_user

SERVER_URL=http://teamcity.uboro.io:8111 # teamcity server URL for agents

# SSL support
VIRTUAL_HOST=teamcity.uboro.io
LETSENCRYPT_HOST=teamcity.uboro.io
LETSENCRYPT_EMAIL=i***@gmail.com
`

**Comment by egregors** [comment]
@pushkin-dev I may take a closer look only  at the weekend

But, for now, you may try to leave `SERVER_URL` like in the example. `server` here is the name of TC service inside the compose. As I remember, you shouldn't set your external address here.

**Comment by pushkin-dev** [comment]
thanks for fast respond, 
I leave SERVER_URL=http://server:8111
but this didn't help.... the same error
`
2021-07-16T11:18:12.355712357Z [2021-07-16 12:18:12,354]  ERROR - s.buildServer.agent.AgentMain2 - Failed to start build agent. For input string: "8111 "
agent_1     | 2021-07-16T11:18:12.355846691Z java.lang.RuntimeException: For input string: "8111 "
`

**Comment by egregors** [comment]
Looks like redundant space in the Port. Check this out, please: https://github.com/JetBrains/teamcity-docker-minimal-agent/issues/5 Probably related.

**Comment by pushkin-dev** [comment]
thanks, all fine worked. with string
`
SERVER_URL=server:8111
`
remove # and comment after
