### ISSUE TITLE
Hello Again :) Trouble with make SSL connection on Cloudflare DNS

### ISSUE THREAD

**Issue by shattershard** [Egregors/teamcity-docker-compose#32]
How can i use your awesome build with Cloudflare?

Im using DigitalOcean + Cloudflare. Also try to connect with make A DNS in my web-server with full SSL encryption. 80 Port is open. But still not works whatever i do. In .env im skip now SSL.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/64084747/163791437-54cade04-14f2-4c91-86c6-fb8a0d4848b8.png">

Also im not changing SSL support in .env

<img width="633" alt="image" src="https://user-images.githubusercontent.com/64084747/163791741-6edd62e5-a1b3-422c-86da-24f3ee7f3435.png">

**Comment by shattershard** [comment]
Also im force HTTPS on Cloudflare.

**Comment by egregors** [comment]
Hi @HarribelHollow! 

Looks like some misunderstanding.

`SERVER_URL` in config file should contain name of your TC server in **internal docker network** (in docker-compose). It's all about internal Docker DNS. Agent isn't available from the outside.

If you are using `docker-compose` file from example, like 
```
# docker-compose.yml

version: '3'

services:
  server:
    image: jetbrains/teamcity-server:latest
# ...
```
It should be `SERVER_URL=http://server:8111`. The same name, as your TC service calls in the `services` section.

**Comment by egregors** [comment]
@HarribelHollow, did you solve the problem? Should I close this issue?
